receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # For Traces to Jaeger - using the OTLP exporter
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # For Metrics to Prometheus - The collector will expose metrics on its own port 8889
  prometheus:
    endpoint: "0.0.0.0:8889"

  # For Logs to Loki
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

  # For debugging the collector itself (optional)
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, logging]

